export const CFG = {
  worldSize: 140,
  terrainSegments: 18,
  daySeconds: 180,
  entityCullDist: 42,
  entityAiDist: 30,
  entityVisibleDist: 40,
  entityAnimDist: 22,
  spawnInvuln: 4,
  player: {
    walkSpeed: 7.5,
    runSpeed: 13,
    sprintBonusNearPrey: 1.15,
    jumpForce: 8.5,
    gravity: 24,
    height: 1.75,
    maxHealth: 100,
    attackRange: 4.2,
    attackDamage: 22,
    attackCooldown: 0.38,
    interactRange: 4.5,
    interactDamage: 18,
    catchRange: 5,
    catchHpRatio: 0.55,
    catchCloseDist: 4.5,
    catchCloseHpRatio: 0.72,
    coyoteTime: 0.12,
    buildReach: 6,
  },
  passive: {
    fleeDist: 11,
    calmDist: 22,
    fleeSpeedMul: 0.68,
    tiredSpeedMul: 0.22,
    corneredSpeedMul: 0.35,
    staminaDrain: 20,
    staminaRegen: 35,
  },
  worldBounds: 0.47,
  decay: { hunger: 0.18, thirst: 0.28 },
  spawn: { tree: 34, rock: 16, bush: 18, deer: 5, rabbit: 5, wolf: 2 },
  camera: {
    dist: 6.5,
    height: 2.8,
    sensX: 0.0022,
    sensY: 0.002,
    smooth: 0.22,
  },
  ui: {
    barsInterval: 0.14,
    labelsInterval: 0.4,
    showWorldLabels: false,
    focusMinDist: 1.8,
  },
  render: {
    dpr: 1,
    maxDt: 0.05,
  },
};

export const ITEMS = {
  wood: { icon: '🪵', name: '木材', type: 'material' },
  stone: { icon: '🪨', name: '石头', type: 'material' },
  fiber: { icon: '🌿', name: '纤维', type: 'material' },
  meat: { icon: '🥩', name: '生肉', type: 'food' },
  cooked_meat: { icon: '🍖', name: '熟肉', type: 'food' },
  stone_axe: { icon: '🪓', name: '石斧', type: 'weapon', slot: 'weapon', attackBonus: 10, interactBonus: 6 },
  wooden_spear: { icon: '🔱', name: '木矛', type: 'weapon', slot: 'weapon', attackBonus: 6, rangeBonus: 0.6 },
  wooden_bow: { icon: '🏹', name: '木弓', type: 'weapon', slot: 'weapon', attackBonus: 4, rangeBonus: 1.2 },
  leather_armor: { icon: '🦺', name: '皮甲', type: 'armor', slot: 'armor', damageReduce: 0.18 },
  backpack: { icon: '🎒', name: '背包', type: 'accessory', slot: 'accessory' },
  rope: { icon: '🪢', name: '绳索', type: 'material' },
  plank: { icon: '🪵', name: '木板', type: 'material' },
};

/** 制作配方：costs 消耗 inventory；equip 自动装备；build 进入放置模式 */
export const RECIPES = {
  cooked_meat: {
    name: '烤肉',
    category: 'food',
    icon: '🍖',
    costs: { meat: 1, wood: 1 },
    yield: { cooked_meat: 1 },
    desc: '恢复饥饿与生命',
  },
  rope: {
    name: '绳索',
    category: 'material',
    icon: '🪢',
    costs: { fiber: 3 },
    yield: { rope: 1 },
    desc: '高级制作材料',
  },
  plank: {
    name: '木板',
    category: 'material',
    icon: '🪵',
    costs: { wood: 2 },
    yield: { plank: 2 },
    desc: '建造用木板',
  },
  stone_axe: {
    name: '石斧',
    category: 'tool',
    icon: '🪓',
    costs: { wood: 2, stone: 3 },
    yield: { stone_axe: 1 },
    equip: 'weapon',
    desc: '攻击+10 · 砍树更快',
  },
  wooden_spear: {
    name: '木矛',
    category: 'weapon',
    icon: '🔱',
    costs: { wood: 4, fiber: 2 },
    yield: { wooden_spear: 1 },
    equip: 'weapon',
    desc: '攻击+6 · 射程更远',
  },
  leather_armor: {
    name: '皮甲',
    category: 'armor',
    icon: '🦺',
    costs: { fiber: 5, meat: 1 },
    yield: { leather_armor: 1 },
    equip: 'armor',
    desc: '减伤 18%',
  },
  backpack: {
    name: '背包',
    category: 'gear',
    icon: '🎒',
    costs: { fiber: 4, wood: 2 },
    yield: { backpack: 1 },
    equip: 'accessory',
    desc: '生存者标配',
  },
  campfire: {
    name: '篝火',
    category: 'build',
    icon: '🔥',
    costs: { wood: 5, stone: 2 },
    build: 'campfire',
    desc: '放置后可烤肉',
  },
  wood_wall: {
    name: '木墙',
    category: 'build',
    icon: '🧱',
    costs: { wood: 6 },
    build: 'wall',
    desc: '阻挡怪物',
  },
  wood_floor: {
    name: '木地板',
    category: 'build',
    icon: '🟫',
    costs: { plank: 2, wood: 2 },
    build: 'floor',
    desc: '平整地面',
  },
  shelter: {
    name: '简易棚屋',
    category: 'build',
    icon: '🏠',
    costs: { plank: 6, wood: 8, stone: 4 },
    build: 'shelter',
    desc: '休息回血',
  },
};

export const BUILD_DEFS = {
  campfire: { hp: 80, radius: 0.9, height: 0.4 },
  wall: { hp: 120, radius: 1.1, height: 2.2, collider: true },
  floor: { hp: 60, radius: 1.4, height: 0.15 },
  shelter: { hp: 200, radius: 2.2, height: 2.8, healAura: 2, collider: true },
};

export const ENTITY_LABELS = {
  tree: '树木',
  rock: '岩石',
  bush: '灌木',
  deer: '鹿',
  rabbit: '野兔',
  wolf: '狼',
  shadow: '暗影',
};

export const RESOURCES = {
  tree: { hp: 50, drop: { wood: 3 }, color: 0x2d6a3e, radius: 1.3, verb: '砍伐' },
  rock: { hp: 60, drop: { stone: 2 }, color: 0x6c757d, radius: 1.0, verb: '开采' },
  bush: { hp: 20, drop: { fiber: 2 }, color: 0x40916c, radius: 0.8, verb: '采集', drink: 18 },
};

export const CREATURES = {
  deer: { hp: 32, speed: 5.5, passive: true, drop: { meat: 2 }, color: 0xa68a64, radius: 1.0 },
  rabbit: { hp: 12, speed: 6.5, passive: true, drop: { meat: 1 }, color: 0xd4a59a, radius: 0.6 },
  wolf: { hp: 55, speed: 7, damage: 12, aggro: 22, color: 0x495057, radius: 1.0, hostile: true },
  shadow: { hp: 90, speed: 6.5, damage: 20, aggro: 26, color: 0x4a148c, nightOnly: true, radius: 1.1, hostile: true },
};
